version: 2
jobs:
  build:

    docker:
      - image: oracle/graalvm-ce:20.0.0

    steps:
      - checkout

      - restore_cache:
          key: brainfuck-jvm-{{ .Branch }}-{{ checksum "pom.xml" }}

      - run:
          name: Install Apache Maven
          command: |
            yum install -y wget
            wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
            yum install -y apache-maven
            mvn -version

      - run:
          name: Install gu tool
          command: $JAVA_HOME/bin/gu install native-image

      - run:
          name: Download dependencies and plugins
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: brainfuck-jvm-{{ .Branch }}-{{ checksum "pom.xml" }}

      - run:
          name: Run tests
          command: |
            mvn -P coverage \
              clean verify sonar:sonar \
              -Dsonar.projectKey=mthmulders_brainfuck-jvm \
              -Dsonar.organization=mthmulders-github \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.coverage.jacoco.xmlReportPaths= \
                launcher/target/site/jacoco/jacoco.xml,\
                language/target/site/jacoco/jacoco.xml,\
                language/target/site/jacoco-it/jacoco.xml,\
                demo-app/target/site/jacoco/jacoco.xml\
              -Dsonar.login=$SONAR_LOGIN

      - save_cache:
          paths:
            - ~/.m2
            - ~/.sonar/cache
          key: brainfuck-jvm-{{ .Branch }}-{{ checksum "pom.xml" }}

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

workflows:
  version: 2
  build:
    jobs:
      - build
