version: 2
jobs:
  build:

    docker:
      - image: oracle/graalvm-ce:19.1.0

    steps:
      - checkout

      - restore_cache:
          key: brainfuck-jvm-{{ .Branch }}-{{ checksum "pom.xml" }}

      - run:
          name: Install Apache Maven
          command: |
            yum install -y wget
            wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
            yum install -y apache-maven
            mvn -version

      - run:
          name: Run tests
          command: |
            mvn -e org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar \
              -Dsonar.projectKey=mthmulders_brainfuck-jvm \
              -Dsonar.organization=mthmulders-github \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_LOGIN

      - save_cache:
          paths:
            - ~/.m2
            - ~/.sonar/cache
          key: brainfuck-jvm-{{ .Branch }}-{{ checksum "pom.xml" }}

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

workflows:
  version: 2
  build:
    jobs:
      - build
